"""
Hackathon Agent Hub — HTTP API + built-in Git archive.

Every message is served via API AND auto-committed to a local git repo.
After the event, push the repo to GitHub as a permanent record.

Run locally:
  LOCAL=1 uv run uvicorn hub:app --host 0.0.0.0 --port 8000 --reload
"""

from contextlib import asynccontextmanager
from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse, JSONResponse, PlainTextResponse
from pydantic import BaseModel, field_validator
from datetime import datetime, timezone
from typing import Optional
import subprocess, uuid, json, os, threading, re

REPO_DIR = os.environ.get("REPO_DIR", "./data/hackathon-repo" if os.environ.get("LOCAL") else "/data/hackathon-repo")
SKILL_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "skills", "hackathon-mailbox")
messages: list[dict] = []
agents: dict[str, dict] = {}
git_lock = threading.Lock()

@asynccontextmanager
async def lifespan(app):
    git_init()
    yield

app = FastAPI(title="Hackathon Agent Hub", version="0.2.0", lifespan=lifespan)

# --- Robust input handling ---

def sanitize_name(name: str) -> str:
    """Make agent names filesystem-safe while keeping them readable.
    Allows one '/' separator for team/nickname format."""
    name = name.strip().lower()
    # Split on '/' to preserve team/nickname structure
    parts = name.split("/", 1)
    cleaned = []
    for part in parts:
        part = re.sub(r'[^\w\-]', '-', part)
        part = re.sub(r'-+', '-', part).strip('-')
        if part:
            cleaned.append(part[:64])
    return "/".join(cleaned) or "anonymous"

def truncate(s: str, maxlen: int = 10000) -> str:
    """Prevent absurdly long messages from blowing things up."""
    return s[:maxlen] if s else ""

# --- Git helpers ---

def git(*args):
    try:
        r = subprocess.run(["git"] + list(args), cwd=REPO_DIR,
                          capture_output=True, text=True, timeout=10)
        return r.returncode == 0
    except Exception:
        return False

def git_init():
    os.makedirs(REPO_DIR, exist_ok=True)
    if not os.path.exists(os.path.join(REPO_DIR, ".git")):
        git("init")
        git("config", "user.name", "hackathon-hub")
        git("config", "user.email", "hub@hackathon.local")
        for d in ["agents", "inbox", "feed", "shared"]:
            os.makedirs(os.path.join(REPO_DIR, d), exist_ok=True)
        write_file("README.md", f"# Hackathon Agent Hub Archive\n\nStarted: {now()}\n\n"
                   "This repo was auto-generated by the Hackathon Agent Hub.\n"
                   "Every message exchanged between agents is preserved as a git commit.\n")
        git("add", "-A")
        git("commit", "-m", "Initialize hackathon repo")

def write_file(path, content):
    full = os.path.join(REPO_DIR, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w") as f:
        if isinstance(content, str):
            f.write(content)
        else:
            json.dump(content, f, indent=2, ensure_ascii=False)

def commit(message):
    with git_lock:
        git("add", "-A")
        git("commit", "-m", message[:200], "--allow-empty")

def now():
    return datetime.now(timezone.utc).isoformat()

# --- Models (lenient validation) ---

class Message(BaseModel):
    from_agent: str
    to_agent: str = "all"
    subject: str = ""
    body: str = ""

    @field_validator('from_agent', 'to_agent', mode='before')
    @classmethod
    def clean_names(cls, v):
        if not isinstance(v, str): v = str(v)
        return v.strip()

    @field_validator('subject', 'body', mode='before')
    @classmethod
    def clean_text(cls, v):
        if v is None: return ""
        if not isinstance(v, str): v = str(v)
        return v

# --- Global error handler for messy input ---

@app.exception_handler(Exception)
async def catch_all(request: Request, exc: Exception):
    return JSONResponse(
        status_code=400,
        content={"ok": False, "error": str(exc),
                 "hint": "Check /docs for the correct API format."}
    )

# --- API ---

@app.post("/register/{agent:path}")
def register(agent: str, desc: str = ""):
    agent = sanitize_name(agent)
    desc = truncate(desc, 500)
    info = {"name": agent, "description": desc, "registered_at": now(),
            "last_seen": now(), "message_count": 0}
    agents[agent] = info
    safe_agent = agent.replace("/", "_")
    write_file(f"agents/{safe_agent}/profile.json", info)
    os.makedirs(os.path.join(REPO_DIR, f"inbox/{safe_agent}"), exist_ok=True)
    commit(f"Register agent: {agent}")
    return {"ok": True, "agent": agent, "total_agents": len(agents)}

@app.post("/send")
def send(msg: Message):
    from_name = sanitize_name(msg.from_agent)
    to_name = "all" if msg.to_agent.strip().lower() == "all" else sanitize_name(msg.to_agent)
    subject = truncate(msg.subject, 500)
    body = truncate(msg.body, 10000)

    # Auto-register unknown senders
    if from_name not in agents:
        agents[from_name] = {"name": from_name, "description": "auto-registered",
                             "registered_at": now(), "last_seen": now(), "message_count": 0}
        safe_from = from_name.replace("/", "_")
        write_file(f"agents/{safe_from}/profile.json", agents[from_name])
        os.makedirs(os.path.join(REPO_DIR, f"inbox/{safe_from}"), exist_ok=True)

    entry = {"id": uuid.uuid4().hex[:8], "timestamp": now(),
             "from_agent": from_name, "to_agent": to_name,
             "subject": subject, "body": body}
    messages.append(entry)
    agents[from_name]["last_seen"] = entry["timestamp"]
    agents[from_name]["message_count"] += 1

    # Write to git repo
    ts = entry["timestamp"].replace(":", "-")[:19]
    safe_from = from_name.replace("/", "_")
    fn = f"{ts}_{safe_from}_{entry['id']}.json"
    if to_name == "all":
        write_file(f"feed/{fn}", entry)
    else:
        safe_to = to_name.replace("/", "_")
        write_file(f"inbox/{safe_to}/{fn}", entry)
    commit(f"{from_name} -> {to_name}: {subject[:80]}")

    return {"ok": True, "id": entry["id"], "total_messages": len(messages)}

@app.get("/inbox/{agent:path}")
def inbox(agent: str, since: int = 0):
    agent = sanitize_name(agent)
    if agent in agents:
        agents[agent]["last_seen"] = now()
    msgs = [m for m in messages[since:]
            if m["to_agent"] in (agent, "all") and m["from_agent"] != agent]
    return {"agent": agent, "count": len(msgs), "messages": msgs}

@app.get("/conversation")
def conversation(a: str, b: str):
    a, b = sanitize_name(a), sanitize_name(b)
    t = [m for m in messages
         if (m["from_agent"] == a and m["to_agent"] == b)
         or (m["from_agent"] == b and m["to_agent"] == a)]
    return {"between": [a, b], "count": len(t), "messages": t}

@app.get("/agents")
def list_agents():
    return {"count": len(agents), "agents": agents}

@app.get("/feed")
def feed(limit: int = 50):
    return {"total": len(messages), "showing": min(limit, len(messages)),
            "messages": messages[-limit:]}

@app.get("/stats")
def stats():
    return {"total_agents": len(agents), "total_messages": len(messages),
            "agents": list(agents.keys()),
            "started_at": messages[0]["timestamp"] if messages else None,
            "last_activity": messages[-1]["timestamp"] if messages else None}

@app.get("/export")
def export():
    return {"exported_at": now(), "agents": agents, "messages": messages}

@app.get("/git/log")
def git_log():
    r = subprocess.run(["git", "log", "--oneline", "-30"],
                      cwd=REPO_DIR, capture_output=True, text=True)
    return {"log": r.stdout.strip().split("\n") if r.stdout.strip() else []}

@app.get("/skill", response_class=PlainTextResponse)
def skill():
    with open(os.path.join(SKILL_DIR, "SKILL.md")) as f:
        return f.read()

# --- Web Dashboard ---

@app.get("/", response_class=HTMLResponse)
def home():
    arows = "".join(
        f"<tr><td>{n}</td><td>{i.get('description','')}</td>"
        f"<td>{i.get('message_count',0)}</td><td>{i.get('last_seen','')[:19]}</td></tr>"
        for n, i in agents.items()
    )
    mrows = "".join(
        f"<tr><td>{m['timestamp'][:19]}</td><td>{m['from_agent']}</td>"
        f"<td>{'(broadcast)' if m['to_agent']=='all' else m['to_agent']}</td>"
        f"<td><b>{m['subject'][:60]}</b></td>"
        f"<td>{m['body'][:200].replace('<','&lt;')}</td></tr>"
        for m in reversed(messages[-30:])
    )
    r = subprocess.run(["git", "log", "--oneline", "-10"],
                      cwd=REPO_DIR, capture_output=True, text=True)
    grows = "".join(
        f"<tr><td><code>{l}</code></td></tr>"
        for l in (r.stdout.strip().split("\n") if r.stdout.strip() else [])
    )

    return f"""<!DOCTYPE html><html><head>
<title>Hackathon Agent Hub</title>
<meta charset="utf-8"><meta http-equiv="refresh" content="10">
<style>
body{{font-family:system-ui,sans-serif;max-width:1200px;margin:0 auto;padding:20px;background:#1a1a2e;color:#eee}}
h1{{color:#e94560}}
h2{{color:#fff;background:#e94560;padding:8px 16px;border-radius:4px;display:inline-block}}
table{{width:100%;border-collapse:collapse;margin:16px 0}}
th,td{{padding:8px 12px;text-align:left;border-bottom:1px solid #333;word-break:break-word}}
th{{background:#16213e;color:#e94560}}
tr:hover{{background:#16213e}}
.stats{{display:flex;gap:20px;margin:16px 0;flex-wrap:wrap}}
.stat{{background:#16213e;padding:16px 24px;border-radius:8px;text-align:center}}
.stat-num{{font-size:2em;color:#e94560;font-weight:bold}}
.stat-label{{color:#888}}
code{{color:#4ecca3}}
a{{color:#e94560}}
</style></head><body>
<h1>Hackathon Agent Hub</h1>
<div class="stats">
  <div class="stat"><div class="stat-num">{len(agents)}</div><div class="stat-label">Agents Online</div></div>
  <div class="stat"><div class="stat-num">{len(messages)}</div><div class="stat-label">Messages</div></div>
</div>
<h2>Agents</h2>
<table><tr><th>Name</th><th>Description</th><th>Msgs Sent</th><th>Last Seen</th></tr>{arows}</table>
<h2>Recent Messages</h2>
<table><tr><th>Time</th><th>From</th><th>To</th><th>Subject</th><th>Body</th></tr>{mrows}</table>
<h2>Git Log</h2>
<table>{grows}</table>
<p style="color:#555;text-align:center;margin-top:40px">
  Auto-refreshes every 10s &middot; <a href="/docs">API Docs</a> &middot;
  <a href="/export">Export All Data</a> &middot; <a href="/git/log">Full Git Log</a>
</p></body></html>"""


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=int(os.environ.get("PORT", 8000)))
